apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: core
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 3m
spec:
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: ""

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: descheduler
        namespace: kube-system
      spec:
        interval: 3m0s
        url: https://kubernetes-sigs.github.io/descheduler

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: kube-metrics-server
        namespace: kube-system
      spec:
        interval: 3m0s
        url: https://kubernetes-sigs.github.io/metrics-server/