apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: gateway-api-crds
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 3m
spec:
  dependsOn:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: helmreleases.helm.toolkit.fluxcd.io
    
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: flux-operator
      namespace: flux-system
      ready: true
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: gateway-api-crds
        namespace: flux-system
      spec:
        interval: 30m
        url: https://github.com/kubernetes-sigs/gateway-api.git
        ref: refs/heads/main

    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: gateway-api-crds
        namespace: flux-system
      spec:
        interval: 15m
        sourceRef:
          kind: GitRepository
          name: gateway-api-crds
          namespace: flux-system
        path: config/crd/experimental
        prune: true