apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: storage
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 3m
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: bootstrap
      namespace: flux-system
      ready: true
  resources:
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: default-storage
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: ebs.csi.eks.amazonaws.com
      volumeBindingMode: WaitForFirstConsumer
      parameters:
        type: gp3