apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/ignore-healthcheck: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.14.0
    helm:
      valuesObject:
        {{- include "operatorNodeSelectors" . | indent 8 }}
        {{- include "operatorTolerations" . | indent 8 }}
        replicas: 3
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        topologySpreadConstraints:
          - topologyKey: "topology.kubernetes.io/zone"
            maxSkew: 1
            minDomains: 3
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: kube-metrics-server
            matchLabelKeys: ["pod-template-hash"]
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true