global:
  nodeSelector:
    node.niovial.io/pool: system
  tolerations:
    - key: node.niovial.io/pool
      operator: Equal
      value: system
redis-ha:
  nodeSelector:
    node.niovial.io/pool: system
  tolerations:
    - key: node.niovial.io/pool
      operator: Equal
      value: system