apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: domain-credentials
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "52"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: homelab-secrets
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 24h
  data:
    - secretKey: domain-secret
      remoteRef:
        key: homelab/cloudflare-dns
        property: niovial.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "40"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: domain-credentials
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "52"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: homelab-secrets
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 24h
  data:
    - secretKey: domain-secret
      remoteRef:
        key: homelab/cloudflare-dns
        property: niovial.io