apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/ignore-healthcheck: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: v1.102.4
    helm:
      valuesObject:
        # https://tailscale.com/docs/kubernetes-operator/manage-and-configure/workload-identity-federation
        oauth:
          clientId: TdWRkjSjua11CNTRL-kS1qtWEvNU11CNTRL
          audience: api.tailscale.com/TdWRkjSjua11CNTRL-kS1qtWEvNU11CNTRL
        operatorConfig:
          nodeSelector:
            node.niovial.io/pool: system
          tolerations:
            - key: node.niovial.io/pool
              operator: Equal
              value: system
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
