apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 10.8.0
    helm:
      valuesObject:
        global:
          {{- include "operatorNodeSelectors" . | indent 10 }}
          {{- include "operatorTolerations" . | indent 10 }}
          topologySpreadConstraints:
            - topologyKey: "topology.kubernetes.io/zone"
              maxSkew: 1
              minDomains: 3
              whenUnsatisfiable: DoNotSchedule
              # ArgoCD helm chart sets label selector automatically
              matchLabelKeys: ["pod-template-hash"]
        # NOTE: HA Config
        controller:
          replicas: 1
        server:
          replicas: 3
        repoServer:
          replicas: 3
        applicationSet:
          replicas: 3
        # redis-ha subchart doesn't use ArgoCD global chart values
        redis-ha:
          enabled: true
          {{- include "operatorTolerations" . | indent 10 }}
          topologySpreadConstraints:
            enabled: true
            topologyKey: "topology.kubernetes.io/zone"
            maxSkew: 1
            whenUnsatisfiable: DoNotSchedule
        configs:
          params:
            server.insecure: true
          cm:
            resource.customizations.health.argoproj.io_Application: |
              hs = {}
              hs.status = "Progressing"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.health ~= nil then
                  hs.status = obj.status.health.status
                  if obj.status.health.message ~= nil then
                    hs.message = obj.status.health.message
                  end
                end
              end
              return hs
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
    syncOptions:
      - ServerSideApply=true