global:
  nodeSelector:
    karpenter.sh/nodepool: system
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
redis-ha:
  nodeSelector:
    karpenter.sh/nodepool: system
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists