apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "32"
    argocd.argoproj.io/ignore-healthcheck: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: istiod
    repoURL: https://blob.istio.io/istio-release/charts
    targetRevision: 1.31.1
    helm:
      valuesObject:
        profile: ambient
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
  