apiVersion: v1
kind: ConfigMap
metadata:
  name: tailnet-gateway-config
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "50"
data:
  deployment: |
    spec:
      replicas: 3
  service: |
    spec:
      loadBalancerClass: tailscale
---
{{- if .Values.components.tailnet.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tailnet-gateway
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "51"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    {{- if .Values.certManager.enabled}}
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Values.certManager.letsEncrypt.environment }}
    {{- end}}
spec:
  gatewayClassName: istio
  infrastructure:
    annotations:
      tailscale.com/hostname: internal-niovial-io
    parametersRef:
      group: ""
      kind: ConfigMap
      name: tailnet-gateway-config
  listeners:
    - name: https
      hostname: "*.internal.niovial.io"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: internal-niovial-io-tls
{{- end }}
