# Either "aws" or "hetzner"
provider: hetzner

system:
  # ArgoCD self-management
  argocd:
    enabled: true
    # chart pathfinder
    chart: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 10.8.0
    namespace: argocd
    # app syncing
    wave: "-1"
    # DO NOT FLIP TO TRUE! Flipping to true can cause ArgoCD to delete itself
    cascadeOnDelete: false
    syncPolicy:
      automated:
        prune: false
      retry:
        limit: 20
        backoff:
          duration: 10s

  spegel:
    enabled: true
    # chart pathfinder
    chart: spegel
    repo: oci://ghcr.io/spegel-org/helm-charts/spegel
    version: 0.7.3
    namespace: spegel
    # app syncing
    wave: "0"
    cascadeOnDelete: true
  
  kube-metrics-server:
    enabled: true
    # chart pathfinder
    chart: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.14.0
    namespace: kube-system
    # app syncing
    wave: "1"
    cascadeOnDelete: true

  descheduler:
    enabled: true
    # chart pathfinder
    chart: descheduler
    repo: https://kubernetes-sigs.github.io/descheduler
    version: 0.36.0
    namespace: kube-system
    # app syncing
    wave: "1"
    cascadeOnDelete: true

  cert-manager:
    enabled: true
    # chart pathfinder
    chart: cert-manager
    repo: oci://quay.io/jetstack/charts/cert-manager
    version: 1.20.2
    namespace: cert-manager
    # app syncing
    wave: "2"
    cascadeOnDelete: true

  irsa-webhook:
    enabled: true
    # chart pathfinder
    chart: amazon-eks-pod-identity-webhook
    repo: https://jkroepke.github.io/helm-charts/
    version: 2.6.5
    namespace: kube-system
    # app syncing
    wave: "20"
    cascadeOnDelete: true

  ack-iam-controller:
    enabled: true
    # chart pathfinder
    chart: iam-chart
    repo: public.ecr.aws/aws-controllers-k8s
    version: 1.9.0
    namespace: ack-system
    # app syncing
    wave: "21"
    cascadeOnDelete: true

  vm-operator:
    enabled: true
    # chart pathfinder
    chart: victoria-metrics-operator
    repo: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator
    version: 0.67.3
    namespace: vm-operator
    # app syncing
    wave: "11"
    cascadeOnDelete: true

  vm-stack:
    enabled: true
    # chart pathfinder
    chart: victoria-metrics-k8s-stack
    repo: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
    version: 0.92.1
    namespace: observability
    # app syncing
    wave: "12"
    cascadeOnDelete: true
    syncPolicy:
      syncOptions:
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
    ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data/admin-password
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  
  external-secrets:
    enabled: true
    # chart pathfinder
    chart: external-secrets
    repo: https://charts.external-secrets.io
    version: 2.10.0
    namespace: external-secrets
    # app syncing
    wave: "30"
    cascadeOnDelete: true

  external-dns:
    enabled: true
    # chart pathfinder
    chart: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.21.1
    namespace: external-dns
    # app syncing
    wave: "41"
    cascadeOnDelete: true

  cloudnative-pg:
    enabled: true
    # chart pathfinder
    chart: cloudnative-pg
    repo: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
    version: 0.29.0
    namespace: cnpg-system
    # app syncing
    wave: "41"
    cascadeOnDelete: true

  barman-cloud-plugin:
    enabled: true
    # chart pathfinder
    chart: plugin-barman-cloud
    repo: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
    version: 0.7.0
    namespace: cnpg-system
    # app syncing
    wave: "42"
    cascadeOnDelete: true

  tailscale-operator:
    enabled: true
    # chart pathfinder
    chart: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: v1.102.4
    namespace: tailscale
    # app syncing
    wave: "50"
    cascadeOnDelete: true

istio:
  enabled: true
  repo: https://blob.istio.io/istio-release/charts
  version: 1.31.1
  namespace: istio-system
  cascadeOnDelete: true
  components:
    istio-base:
      chart: base
      wave: "10"
    istiod:
      chart: istiod
      wave: "13"
    istio-cni:
      chart: cni
      wave: "14"
    ztunnel:
      chart: ztunnel
      wave: "15"

# Repository containing values for all applications in this chart 
config:
  repo: https://github.com/rtnkwami/homelab.git
  path: charts/platform/config

# AWS specific config for iam, secrets, etc., when using hetzner
aws:
  accountId: "913509421780"
  region: us-east-1
  ack:
    enabled: false

certManager:  
  letsEncrypt:
    environment: staging
    email: cert-alerts@niovial.io

  clusterIssuer:
    enabled: false

descheduler:
  enabled: true

# Requires provider: "hetzner"
spegel:
  enabled: false

victoriaMetrics:
  enabled: true

# Requires: aws.ack.enabled to be "true"
externalSecrets:
  enabled: false

tailscale:
  enabled: false

  services:
    enabled: true

# Requies certManager.clusterIssuer.enabled to be true
appGateway:
  annotations:
    load-balancer.hetzner.cloud/name: "app-gateway"
    load-balancer.hetzner.cloud/location: "nbg1"