apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/ignore-healthcheck: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: base
    repoURL: https://blob.istio.io/istio-release/charts
    targetRevision: 1.31.1
    helm:
      valuesObject:
        # https://istio.io/latest/docs/ambient/install/helm/#:~:text=If%20you%20apply,automatically
        base:
          validationFailurePolicy: Fail
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
  