# Either "aws" or "hetzner"
provider: hetzner
# Requires provider: "aws"
aws:
  accountId: "913509421780"
  region: us-east-1
  ack:
    enabled: false

istio:
  enabled: true
  istiod:
    enabled: true
  ztunnel:
    enabled: true
  cni:
    enabled: true

certManager:
  enabled: false
  
  letsEncrypt:
    environment: staging
    email: cert-alerts@niovial.io

descheduler:
  enabled: true

# Requires provider: "hetzner"
spegel:
  enabled: false

victoriaMetrics:
  enabled: true

gateway:
  infrastructureAnnotations:
    load-balancer.hetzner.cloud/name: "app-gateway"
    load-balancer.hetzner.cloud/location: "nbg1"

components:
  tailnet:
    enabled: true