apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/ignore-healthcheck: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.20.1
    helm:
      valuesObject:
        topologySpreadConstraints:
          operator:
            - topologyKey: "topology.kubernetes.io/zone"
              maxSkew: 1
              minDomains: 3
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: keda
              matchLabelKeys: ["pod-template-hash"]
          metricsServer:
            - topologyKey: "topology.kubernetes.io/zone"
              maxSkew: 1
              minDomains: 3
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: keda
              matchLabelKeys: ["pod-template-hash"]
          webhooks:
            - topologyKey: "topology.kubernetes.io/zone"
              maxSkew: 1
              minDomains: 3
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: keda
              matchLabelKeys: ["pod-template-hash"]
        operator:
          replicaCount: 3
          nodeSelector:
            node.niovial.io/pool: system
          tolerations:
            - key: node.niovial.io/pool
              operator: Equal
              value: system
        metricsServer:
          replicaCount: 3
          nodeSelector:
            node.niovial.io/pool: system
          tolerations:
            - key: node.niovial.io/pool
              operator: Equal
              value: system
        webhooks:
          replicaCount: 3
          nodeSelector:
            node.niovial.io/pool: system
          tolerations:
            - key: node.niovial.io/pool
              operator: Equal
              value: system
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true