{{- if .Values.tailscale.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    argocd.argoproj.io/ignore-healthcheck: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: v1.102.4
    helm:
      valuesObject:
        # https://tailscale.com/docs/kubernetes-operator/manage-and-configure/workload-identity-federation
        oauth:
          clientId: {{ .Values.tailscale.operatorOauth.clientId }}
          audience: {{ .Values.tailscale.operatorOauth.audience }}
        operatorConfig:
          {{- include "operatorNodeSelectors" . | indent 10 }}
          {{- include "operatorTolerations" . | indent 10 }}
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
{{- end }}