{{- if .Values.spegel.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: spegel
  labels:
    pod-security.kubernetes.io/enforce: privileged
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
{{- end }}
{{- if .Values.istio.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
{{- end }}
{{- if .Values.victoriaMetrics.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: observability-agents
  labels:
    pod-security.kubernetes.io/enforce: privileged
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
{{- end }}
{{- if .Values.tailscale.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    pod-security.kubernetes.io/enforce: privileged
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
{{- if .Values.victoriaMetrics.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: vm-operator
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
{{- end }}
{{- if .Values.victoriaMetrics.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
{{- end }}
{{- if .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
---
{{- if and (eq .Values.provider "hetzner") .Values.aws.ack.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: ack-system
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
{{- end }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-options: Delete=false