{{- range $component, $settings := .Values.system }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $settings.namespace }}
  {{- with $settings.namespaceLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $settings.namespaceAnnotations }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{ end -}}