apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: homelab-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "51"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}

