apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "41"
    argocd.argoproj.io/ignore-healthcheck: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: victoria-metrics-k8s-stack
    repoURL: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
    # Release peer of VM Operator is 0.67.3
    targetRevision: 0.92.1
    helm:
      valuesObject:
        victoria-metrics-operator:
          enabled: false
        # NOTE: Metrics Configuration
        vmsingle:
          spec:
            removePvcAfterDelete: true
            nodeSelector:
              node.niovial.io/pool: database
            tolerations:
              - key: node.niovial.io/pool
                operator: Equal
                value: database
        prometheus-node-exporter:
          namespaceOverride: observability-agents
        # NOTE:
        # Enable this metric for node pools metrics
        kube-state-metrics:
          metricAllowList:
            - kube_node_labels
        # NOTE: Logs Configuration
        vlsingle:
          enabled: true
          spec:
            nodeSelector:
              node.niovial.io/pool: database
            tolerations:
              - key: node.niovial.io/pool
                operator: Equal
                value: database
        vlagent:
          enabled: true
          namespaceOverride: observability-agents
          spec:
            tolerations:
              - operator: Exists
        grafana:
          plugins:
            - victoriametrics-logs-datasource
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data/admin-password
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true