{{- if .Values.certManager.clusterIssuer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-gateway-config
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "40"
data:
  horizontalPodAutoscaler: |
    spec:
      minReplicas: 3
      maxReplicas: 6
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: app-gateway
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "42"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Values.certManager.letsEncrypt.environment }}
spec:
  gatewayClassName: istio
  infrastructure:
    {{- with .Values.appGateway.annotations }}
    annotations:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    parametersRef:
      group: ""
      kind: ConfigMap
      name: app-gateway-config
  listeners:
    - name: https
      hostname: "*.niovial.io"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: niovial-io-tls
{{- end }}