apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.9.x"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
  cluster:
    type: kubernetes
    size: medium
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux
  kustomize:
    patches:
      - target:
          kind: Deployment
        patch: |
          - op: add
            path: /spec/replicas
            value: 3
          
          - op: add
            path: /spec/template/spec/topologySpreadConstraints
            value:
              - topologyKey: "topology.kubernetes.io/zone"
                maxSkew: 1
                minDomains: 3
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: flux
                matchLabelKeys: ["pod-template-hash"]
  sync:
    kind: GitRepository
    url: https://github.com/rtnkwami/homelab.git
    ref: refs/heads/refactor/gitops
    path: gitops/workloads