replicaCount: 3
nodeSelector:
  node.niovial.io/pool: system
tolerations:
  - key: node.niovial.io/pool
    operator: Equal
    value: system
topologySpreadConstraints:
  - topologyKey: "topology.kubernetes.io/zone"
    maxSkew: 1
    minDomains: 3
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: cloudnative-pg
    matchLabelKeys: ["pod-template-hash"]