kind: Deployment
leaderElection:
  enabled: true
podDisruptionBudget:
  enabled: true
replicas: 3
topologySpreadConstraints:
  - topologyKey: "topology.kubernetes.io/zone"
    maxSkew: 1
    minDomains: 3
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: descheduler
    matchLabelKeys: ["pod-template-hash"]
deschedulerPolicy:
  maxNoOfPodsToEvictPerNode: 10
  maxNoOfPodsToEvictPerNamespace: 10
  # https://github.com/kubernetes-sigs/descheduler/blob/master/README.md
  profiles:
    - name: default
      pluginConfig:
        - name: DefaultEvictor
          args:
            nodeFit: true
            minReplicas: 2
            podProtections:
              defaultDisabled:
              - "PodsWithLocalStorage"
              extraEnabled:
              - "PodsWithPVC"
        - name: RemoveDuplicates
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 100
            includingInitContainers: true
        - name: RemovePodsViolatingNodeAffinity
          args:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        - name: RemovePodsViolatingNodeTaints
        - name: RemovePodsViolatingInterPodAntiAffinity
        - name: RemovePodsViolatingTopologySpreadConstraint
      plugins:
        balance:
          enabled:
            - RemoveDuplicates
            - RemovePodsViolatingTopologySpreadConstraint
        deschedule:
          enabled:
            - RemovePodsHavingTooManyRestarts
            - RemovePodsViolatingNodeTaints
            - RemovePodsViolatingNodeAffinity
            - RemovePodsViolatingInterPodAntiAffinity