global:
  nodeSelector:
    node.niovial.io/pool: system
  tolerations:
    - key: node.niovial.io/pool
      operator: Equal
      value: system
  topologySpreadConstraints:
    - topologyKey: "topology.kubernetes.io/zone"
      maxSkew: 1
      minDomains: 3
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: external-secrets
      matchLabelKeys: ["pod-template-hash"]
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/external-secrets-operator
replicaCount: 3
leaderElect: true
podDisruptionBudget:
  enabled: true
webhook:
  replicaCount: 3
  podDisruptionBudget:
    enabled: true
certController:
  replicaCount: 3
  podDisruptionBudget:
    enabled: true