nodeSelector:
  node.niovial.io/pool: system
tolerations:
  - key: node.niovial.io/pool
    operator: Equal
    value: system
replicas: 3
podDisruptionBudget:
  enabled: true
  minAvailable: 1
topologySpreadConstraints:
  - topologyKey: "topology.kubernetes.io/zone"
    maxSkew: 1
    minDomains: 3
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: kube-metrics-server
    matchLabelKeys: ["pod-template-hash"]